apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - opentelemetry-operator.yml
  - cluster-observability.yml

patches:
  - path: opentelemetry-operator-patch.yml
    target:
      kind: Deployment
      name: opentelemetry-operator-controller-manager
