---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-cloud
  namespace: kadras-system
spec:
  interval: 1m
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: gitops-configurer
  path: ./apps/cloud
  targetNamespace: apps
  prune: true
  wait: true
  force: true
